from django.core.management.base import BaseCommand

from rental.models import Vehicle


class Command(BaseCommand):
    help = "Seed the database with Zanzibar-focused rental vehicles and scooters."

    def handle(self, *args, **options):
        vehicles = [
            {
                "name": "Toyota Ist | ZNZ 214K",
                "brand": "Toyota",
                "model": "Ist",
                "year": 2005,
                "vehicle_type": "car",
                "body_type": "sedan",
                "seats": 5,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Stone Town",
                "daily_rate": "32.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/2002-2005%20Toyota%20ist.jpg",
                "description": "Compact Zanzibar town car with a local plate style and easy city handling.",
                "is_trending": True,
            },
            {
                "name": "Toyota Spacio | ZNZ 533F",
                "brand": "Toyota",
                "model": "Spacio",
                "year": 2004,
                "vehicle_type": "car",
                "body_type": "van",
                "seats": 7,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Amani",
                "daily_rate": "38.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Corolla%20Spacio%2001.jpg",
                "description": "Family-friendly wagon popular for school runs, errands, and hotel pickups.",
                "is_trending": True,
            },
            {
                "name": "Toyota Prado | ZNZ 808P",
                "brand": "Toyota",
                "model": "Land Cruiser Prado",
                "year": 2018,
                "vehicle_type": "car",
                "body_type": "suv",
                "seats": 7,
                "transmission": "Automatic",
                "fuel_type": "Diesel",
                "location": "Kiwengwa",
                "daily_rate": "115.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Land%20Cruiser%20Prado%20%2854098221407%29.jpg",
                "description": "Safari-capable SUV for beach transfers, rough roads, and long drives.",
                "is_trending": True,
            },
            {
                "name": "Toyota Land Cruiser | ZNZ 901V",
                "brand": "Toyota",
                "model": "Land Cruiser",
                "year": 2020,
                "vehicle_type": "car",
                "body_type": "luxury",
                "seats": 8,
                "transmission": "Automatic",
                "fuel_type": "Diesel",
                "location": "Nungwi",
                "daily_rate": "135.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Land%20Cruiser%20200%204x4%20VXR%202020.jpg",
                "description": "Heavy-duty Land Cruiser for premium tours and island-wide travel.",
                "is_trending": True,
            },
            {
                "name": "Toyota Alphard | ZNZ 447A",
                "brand": "Toyota",
                "model": "Alphard",
                "year": 2018,
                "vehicle_type": "car",
                "body_type": "van",
                "seats": 7,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Airport Branch",
                "daily_rate": "98.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/2018%20Toyota%20Alphard%20V6%20%28front%29.jpg",
                "description": "Executive people mover ideal for VIP airport transfers and family groups.",
            },
            {
                "name": "Toyota Vellfire | ZNZ 552L",
                "brand": "Toyota",
                "model": "Vellfire",
                "year": 2013,
                "vehicle_type": "car",
                "body_type": "van",
                "seats": 7,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Paje",
                "daily_rate": "102.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/2011-2015%20Toyota%20Vellfire.jpg",
                "description": "Premium van with lounge-style comfort for weddings, hotels, and tours.",
            },
            {
                "name": "Toyota Vanguard | ZNZ 618R",
                "brand": "Toyota",
                "model": "Vanguard",
                "year": 2008,
                "vehicle_type": "car",
                "body_type": "suv",
                "seats": 5,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Mwanakwerekwe",
                "daily_rate": "72.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Vanguard.JPG",
                "description": "Balanced SUV for town driving with enough space for trips around Zanzibar.",
            },
            {
                "name": "Toyota RAV4 | ZNZ 335M",
                "brand": "Toyota",
                "model": "RAV4",
                "year": 2009,
                "vehicle_type": "car",
                "body_type": "suv",
                "seats": 5,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Kisauni",
                "daily_rate": "68.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Rav4.jpg",
                "description": "Reliable urban SUV suited for daily rentals and business travel.",
            },
            {
                "name": "Suzuki Escudo | ZNZ 120S",
                "brand": "Suzuki",
                "model": "Escudo",
                "year": 2007,
                "vehicle_type": "car",
                "body_type": "suv",
                "seats": 5,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Mpendae",
                "daily_rate": "61.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/2005-2008%20Suzuki%20Escudo%205dr%201.png",
                "description": "Compact 4x4 that fits both island roads and everyday family use.",
            },
            {
                "name": "Jeep Wrangler | ZNZ 786J",
                "brand": "Jeep",
                "model": "Wrangler",
                "year": 2020,
                "vehicle_type": "car",
                "body_type": "pickup",
                "seats": 5,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Jambiani",
                "daily_rate": "128.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Jeep%20Wrangler%20%2849514043693%29.jpg",
                "description": "Adventure-focused Wrangler for premium off-road beach and village routes.",
            },
            {
                "name": "Honda Today",
                "brand": "Honda",
                "model": "Today",
                "year": 2015,
                "vehicle_type": "scooter",
                "body_type": "sedan",
                "seats": 2,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Stone Town",
                "daily_rate": "14.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Honda%20Today.jpg",
                "description": "Simple everyday scooter for quick rides through Stone Town lanes.",
            },
            {
                "name": "Honda Click 150",
                "brand": "Honda",
                "model": "Click 150",
                "year": 2019,
                "vehicle_type": "scooter",
                "body_type": "sedan",
                "seats": 2,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Mbweni",
                "daily_rate": "16.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Honda%20Click%20150%20version%202%20model%202019.jpg",
                "description": "Sporty scooter with enough pace for daily dealer and delivery rides.",
            },
            {
                "name": "Honda Vario 150",
                "brand": "Honda",
                "model": "Vario 150",
                "year": 2018,
                "vehicle_type": "scooter",
                "body_type": "sedan",
                "seats": 2,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Fumba",
                "daily_rate": "17.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/2016%20Honda%20Vario%20150%20%2812-20-2018%29%2C%20South%20Tangerang.jpg",
                "description": "Popular 150 cc scooter for fast town travel and fuel-friendly rentals.",
            },
            {
                "name": "Honda Vario 160",
                "brand": "Honda",
                "model": "Vario 160",
                "year": 2023,
                "vehicle_type": "scooter",
                "body_type": "sedan",
                "seats": 2,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Bububu",
                "daily_rate": "18.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Vario%20160%202023.png",
                "description": "Sharper, newer Vario option for riders who want more power and style.",
            },
            {
                "name": "Yamaha Grand Filano",
                "brand": "Yamaha",
                "model": "Grand Filano",
                "year": 2015,
                "vehicle_type": "scooter",
                "body_type": "sedan",
                "seats": 2,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Kilimani",
                "daily_rate": "18.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/2015%20Yamaha%20Grand%20Filano%20125%20%2820150604%29.jpg",
                "description": "Retro-styled scooter with comfortable city ergonomics and easy parking.",
            },
            {
                "name": "Vespa Primavera",
                "brand": "Vespa",
                "model": "Primavera",
                "year": 2026,
                "vehicle_type": "scooter",
                "body_type": "sedan",
                "seats": 2,
                "transmission": "Automatic",
                "fuel_type": "Petrol",
                "location": "Forodhani",
                "daily_rate": "22.00",
                "image_url": "https://commons.wikimedia.org/wiki/Special:FilePath/Vespa%20Primavera%2080th%202026.jpg",
                "description": "Classic Vespa look for premium scooter hires and stylish beach-town riding.",
            },
        ]

        created = 0
        for data in vehicles:
            defaults = {key: value for key, value in data.items() if key != "name"}
            _, was_created = Vehicle.objects.get_or_create(name=data["name"], defaults=defaults)
            created += int(was_created)

        self.stdout.write(self.style.SUCCESS(f"Seed complete. Created {created} vehicles."))
