const commonsThumb = (fileName, width = 900) =>
  `https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(fileName)}?width=${width}`;

export const fallbackVehicles = [
  {
    id: "znz-ist-214",
    name: "Toyota Ist | ZNZ 214K",
    brand: "Toyota",
    model: "Ist",
    bodyTypeLabel: "City hatchback",
    dailyRate: 32,
    imageUrl: commonsThumb("2002-2005 Toyota ist.jpg", 720),
  },
  {
    id: "znz-spacio-533",
    name: "Toyota Spacio | ZNZ 533F",
    brand: "Toyota",
    model: "Spacio",
    bodyTypeLabel: "Family wagon",
    dailyRate: 38,
    imageUrl: commonsThumb("Toyota Corolla Spacio 01.jpg", 720),
  },
  {
    id: "znz-prado-808",
    name: "Toyota Prado | ZNZ 808P",
    brand: "Toyota",
    model: "Land Cruiser Prado",
    bodyTypeLabel: "Safari SUV",
    dailyRate: 115,
    imageUrl: commonsThumb("Toyota Land Cruiser Prado (54098221407).jpg", 720),
  },
  {
    id: "znz-landcruiser-901",
    name: "Toyota Land Cruiser | ZNZ 901V",
    brand: "Toyota",
    model: "Land Cruiser",
    bodyTypeLabel: "Full-size 4x4",
    dailyRate: 135,
    imageUrl: commonsThumb("Toyota Land Cruiser 200 4x4 VXR 2020.jpg", 720),
  },
  {
    id: "znz-alphard-447",
    name: "Toyota Alphard | ZNZ 447A",
    brand: "Toyota",
    model: "Alphard",
    bodyTypeLabel: "Executive van",
    dailyRate: 98,
    imageUrl: commonsThumb("2018 Toyota Alphard V6 (front).jpg", 720),
  },
  {
    id: "znz-vellfire-552",
    name: "Toyota Vellfire | ZNZ 552L",
    brand: "Toyota",
    model: "Vellfire",
    bodyTypeLabel: "Premium van",
    dailyRate: 102,
    imageUrl: commonsThumb("2011-2015 Toyota Vellfire.jpg", 720),
  },
  {
    id: "znz-vanguard-618",
    name: "Toyota Vanguard | ZNZ 618R",
    brand: "Toyota",
    model: "Vanguard",
    bodyTypeLabel: "Mid-size SUV",
    dailyRate: 72,
    imageUrl: commonsThumb("Toyota Vanguard.JPG", 720),
  },
  {
    id: "znz-rav4-335",
    name: "Toyota RAV4 | ZNZ 335M",
    brand: "Toyota",
    model: "RAV4",
    bodyTypeLabel: "Urban SUV",
    dailyRate: 68,
    imageUrl: commonsThumb("Toyota Rav4.jpg", 720),
  },
  {
    id: "znz-escudo-120",
    name: "Suzuki Escudo | ZNZ 120S",
    brand: "Suzuki",
    model: "Escudo",
    bodyTypeLabel: "Compact 4x4",
    dailyRate: 61,
    imageUrl: commonsThumb("2005-2008 Suzuki Escudo 5dr 1.png", 720),
  },
  {
    id: "znz-jeep-786",
    name: "Jeep Wrangler | ZNZ 786J",
    brand: "Jeep",
    model: "Wrangler",
    bodyTypeLabel: "Open-top 4x4",
    dailyRate: 128,
    imageUrl: commonsThumb("Jeep Wrangler (49514043693).jpg", 720),
  },
  {
    id: "scooter-today-45",
    name: "Honda Today",
    brand: "Honda",
    model: "Today",
    bodyTypeLabel: "Scooter",
    dailyRate: 14,
    imageUrl: commonsThumb("Honda Today.jpg", 720),
  },
  {
    id: "scooter-click-150",
    name: "Honda Click 150",
    brand: "Honda",
    model: "Click 150",
    bodyTypeLabel: "Scooter",
    dailyRate: 16,
    imageUrl: commonsThumb("Honda Click 150 version 2 model 2019.jpg", 720),
  },
  {
    id: "scooter-vario-150",
    name: "Honda Vario 150",
    brand: "Honda",
    model: "Vario 150",
    bodyTypeLabel: "Scooter",
    dailyRate: 17,
    imageUrl: commonsThumb("2016 Honda Vario 150 (12-20-2018), South Tangerang.jpg", 720),
  },
  {
    id: "scooter-vario-160",
    name: "Honda Vario 160",
    brand: "Honda",
    model: "Vario 160",
    bodyTypeLabel: "Scooter",
    dailyRate: 18,
    imageUrl: commonsThumb("Vario 160 2023.png", 720),
  },
  {
    id: "scooter-filano",
    name: "Yamaha Grand Filano",
    brand: "Yamaha",
    model: "Grand Filano",
    bodyTypeLabel: "Scooter",
    dailyRate: 18,
    imageUrl: commonsThumb("2015 Yamaha Grand Filano 125 (20150604).jpg", 720),
  },
  {
    id: "scooter-vespa",
    name: "Vespa Primavera",
    brand: "Vespa",
    model: "Primavera",
    bodyTypeLabel: "Scooter",
    dailyRate: 22,
    imageUrl: commonsThumb("Vespa Primavera 80th 2026.jpg", 720),
  },
];

export const categories = [
  {
    title: "Zanzibar City Cars",
    image: commonsThumb("2002-2005 Toyota ist.jpg", 640),
    tone: "mist",
  },
  {
    title: "Family Vans",
    image: commonsThumb("2018 Toyota Alphard V6 (front).jpg", 640),
    tone: "light",
  },
  {
    title: "Safari SUVs",
    image: commonsThumb("Toyota Land Cruiser Prado (54098221407).jpg", 640),
    tone: "dark",
  },
  {
    title: "Scooters",
    image: commonsThumb("2015 Yamaha Grand Filano 125 (20150604).jpg", 640),
    tone: "silver",
  },
];

export const homeHeroImage = commonsThumb("Toyota Land Cruiser Prado (54098221407).jpg", 1200);
export const homePromoImage = commonsThumb("Toyota Land Cruiser 200 4x4 VXR 2020.jpg", 1200);
