export const fallbackVehicles = [
  {
    id: "znz-ist-214",
    name: "Toyota Ist | ZNZ 214K",
    brand: "Toyota",
    model: "Ist",
    bodyTypeLabel: "City hatchback",
    dailyRate: 32,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/2002-2005%20Toyota%20ist.jpg",
  },
  {
    id: "znz-spacio-533",
    name: "Toyota Spacio | ZNZ 533F",
    brand: "Toyota",
    model: "Spacio",
    bodyTypeLabel: "Family wagon",
    dailyRate: 38,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Corolla%20Spacio%2001.jpg",
  },
  {
    id: "znz-prado-808",
    name: "Toyota Prado | ZNZ 808P",
    brand: "Toyota",
    model: "Land Cruiser Prado",
    bodyTypeLabel: "Safari SUV",
    dailyRate: 115,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Land%20Cruiser%20Prado%20%2854098221407%29.jpg",
  },
  {
    id: "znz-landcruiser-901",
    name: "Toyota Land Cruiser | ZNZ 901V",
    brand: "Toyota",
    model: "Land Cruiser",
    bodyTypeLabel: "Full-size 4x4",
    dailyRate: 135,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Land%20Cruiser%20200%204x4%20VXR%202020.jpg",
  },
  {
    id: "znz-alphard-447",
    name: "Toyota Alphard | ZNZ 447A",
    brand: "Toyota",
    model: "Alphard",
    bodyTypeLabel: "Executive van",
    dailyRate: 98,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/2018%20Toyota%20Alphard%20V6%20%28front%29.jpg",
  },
  {
    id: "znz-vellfire-552",
    name: "Toyota Vellfire | ZNZ 552L",
    brand: "Toyota",
    model: "Vellfire",
    bodyTypeLabel: "Premium van",
    dailyRate: 102,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/2011-2015%20Toyota%20Vellfire.jpg",
  },
  {
    id: "znz-vanguard-618",
    name: "Toyota Vanguard | ZNZ 618R",
    brand: "Toyota",
    model: "Vanguard",
    bodyTypeLabel: "Mid-size SUV",
    dailyRate: 72,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Vanguard.JPG",
  },
  {
    id: "znz-rav4-335",
    name: "Toyota RAV4 | ZNZ 335M",
    brand: "Toyota",
    model: "RAV4",
    bodyTypeLabel: "Urban SUV",
    dailyRate: 68,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Rav4.jpg",
  },
  {
    id: "znz-escudo-120",
    name: "Suzuki Escudo | ZNZ 120S",
    brand: "Suzuki",
    model: "Escudo",
    bodyTypeLabel: "Compact 4x4",
    dailyRate: 61,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/2005-2008%20Suzuki%20Escudo%205dr%201.png",
  },
  {
    id: "znz-jeep-786",
    name: "Jeep Wrangler | ZNZ 786J",
    brand: "Jeep",
    model: "Wrangler",
    bodyTypeLabel: "Open-top 4x4",
    dailyRate: 128,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Jeep%20Wrangler%20%2849514043693%29.jpg",
  },
  {
    id: "scooter-today-45",
    name: "Honda Today",
    brand: "Honda",
    model: "Today",
    bodyTypeLabel: "Scooter",
    dailyRate: 14,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Honda%20Today.jpg",
  },
  {
    id: "scooter-click-150",
    name: "Honda Click 150",
    brand: "Honda",
    model: "Click 150",
    bodyTypeLabel: "Scooter",
    dailyRate: 16,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Honda%20Click%20150%20version%202%20model%202019.jpg",
  },
  {
    id: "scooter-vario-150",
    name: "Honda Vario 150",
    brand: "Honda",
    model: "Vario 150",
    bodyTypeLabel: "Scooter",
    dailyRate: 17,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/2016%20Honda%20Vario%20150%20%2812-20-2018%29%2C%20South%20Tangerang.jpg",
  },
  {
    id: "scooter-vario-160",
    name: "Honda Vario 160",
    brand: "Honda",
    model: "Vario 160",
    bodyTypeLabel: "Scooter",
    dailyRate: 18,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Vario%20160%202023.png",
  },
  {
    id: "scooter-filano",
    name: "Yamaha Grand Filano",
    brand: "Yamaha",
    model: "Grand Filano",
    bodyTypeLabel: "Scooter",
    dailyRate: 18,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/2015%20Yamaha%20Grand%20Filano%20125%20%2820150604%29.jpg",
  },
  {
    id: "scooter-vespa",
    name: "Vespa Primavera",
    brand: "Vespa",
    model: "Primavera",
    bodyTypeLabel: "Scooter",
    dailyRate: 22,
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Vespa%20Primavera%2080th%202026.jpg",
  },
];

export const categories = [
  {
    title: "Zanzibar City Cars",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/2002-2005%20Toyota%20ist.jpg",
    tone: "mist",
  },
  {
    title: "Family Vans",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/2018%20Toyota%20Alphard%20V6%20%28front%29.jpg",
    tone: "light",
  },
  {
    title: "Safari SUVs",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Toyota%20Land%20Cruiser%20Prado%20%2854098221407%29.jpg",
    tone: "dark",
  },
  {
    title: "Scooters",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/2015%20Yamaha%20Grand%20Filano%20125%20%2820150604%29.jpg",
    tone: "silver",
  },
];
